# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
